export const errorCodes = {
  invalidRequest: 'invalid_request',
  invalidCredentials: 'invalid_credentials',
  duplicatePhone: 'duplicate_phone',
  invitationNotFound: 'invitation_not_found',
  userNotFound: 'user_not_found',
  duplicateEstablishment: 'duplicate_establishment',
  duplicateNetwork: 'duplicate_network',
  networkNotFound: 'network_not_found',
  establishmentNotFound: 'establishment_not_found',
  tableNotFound: 'table_not_found',
  duplicateTableNumber: 'duplicate_table_number',
  categoryNotFound: 'category_not_found',
  duplicateCategoryName: 'duplicate_category_name',
  categoryDeleteForbidden: 'category_delete_forbidden',
  productNotFound: 'product_not_found',
  duplicateProductName: 'duplicate_product_name',
} as const;
