export enum PermissionType {
  menuView = 1,
  menuEdit,
  ordersView,
  ordersEdit,
  ordersChangeStatus,
  analyticsView,
  establishmentsView,
  establishmentsEdit,
  usersView,
  usersEdit,
  usersInvite,
  usersRolesEdit,
  settingsView,
  settingsEdit,
}
