import type { PermissionGroup } from '@/types/roles';

export enum PermissionType {
  ordersView = 1,
  ordersCreate,
  ordersEdit,
  ordersTakeInWork,
  ordersSendToKitchen,
  ordersStartCooking,
  ordersMarkReady,
  ordersReturn,
  ordersComplete,
  ordersCancel,
  ordersDelete,

  usersView,
  usersEdit,
  usersDelete,

  invitationsView,
  invitationsCreate,
  invitationsDelete,

  rolesView,
  rolesCreate,
  rolesUpdate,
  rolesDelete,

  establishmentsCreate,
  establishmentsUpdate,
  establishmentsDelete,

  networkEdit,

  tablesView,
  tablesCreate,
  tablesEdit,
  tablesDelete,

  productsView,
  productsCreate,
  productsEdit,
  productsDelete,

  categoriesView,
  categoriesCreate,
  categoriesEdit,
  categoriesDelete,
}

export const PERMISSION_GROUPS: PermissionGroup[] = [
  {
    name: 'Меню',
    permissions: [
      PermissionType.productsView,
      PermissionType.productsCreate,
      PermissionType.productsEdit,
      PermissionType.productsDelete,
      PermissionType.categoriesView,
      PermissionType.categoriesCreate,
      PermissionType.categoriesEdit,
      PermissionType.categoriesDelete,
    ],
  },
  {
    name: 'Замовлення',
    permissions: [
      PermissionType.ordersView,
      PermissionType.ordersCreate,
      PermissionType.ordersEdit,
      PermissionType.ordersTakeInWork,
      PermissionType.ordersSendToKitchen,
      PermissionType.ordersStartCooking,
      PermissionType.ordersMarkReady,
      PermissionType.ordersReturn,
      PermissionType.ordersComplete,
      PermissionType.ordersCancel,
      PermissionType.ordersDelete,
    ],
  },
  {
    name: 'Заклади',
    permissions: [
      PermissionType.establishmentsCreate,
      PermissionType.establishmentsUpdate,
      PermissionType.establishmentsDelete,
      PermissionType.networkEdit,
      PermissionType.tablesView,
      PermissionType.tablesCreate,
      PermissionType.tablesEdit,
      PermissionType.tablesDelete,
    ],
  },
  {
    name: 'Користувачі',
    permissions: [
      PermissionType.usersView,
      PermissionType.usersEdit,
      PermissionType.usersDelete,
      PermissionType.invitationsView,
      PermissionType.invitationsCreate,
      PermissionType.invitationsDelete,
      PermissionType.rolesView,
      PermissionType.rolesUpdate,
      PermissionType.rolesCreate,
      PermissionType.rolesDelete,
    ],
  },
];

export const PERMISSION_LABELS: Record<PermissionType, string> = {
  [PermissionType.productsView]: 'Перегляд меню',
  [PermissionType.productsCreate]: 'Створення страв',
  [PermissionType.productsEdit]: 'Редагування страв',
  [PermissionType.productsDelete]: 'Видалення страв',
  [PermissionType.categoriesView]: 'Перегляд категорій',
  [PermissionType.categoriesCreate]: 'Створення категорій',
  [PermissionType.categoriesEdit]: 'Редагування категорій',
  [PermissionType.categoriesDelete]: 'Видалення категорій',
  [PermissionType.ordersView]: 'Перегляд замовлень',
  [PermissionType.ordersCreate]: 'Створення замовлення',
  [PermissionType.ordersEdit]: 'Редагування замовлень',
  [PermissionType.ordersTakeInWork]: 'Взяти у роботу',
  [PermissionType.ordersSendToKitchen]: 'Відправити на кухню',
  [PermissionType.ordersStartCooking]: 'Розпочати готування',
  [PermissionType.ordersMarkReady]: 'Позначити як приготовлене',
  [PermissionType.ordersReturn]: 'Повернути замовлення на попередній статус',
  [PermissionType.ordersComplete]: 'Завершити замовлення',
  [PermissionType.ordersCancel]: 'Скасувати замовлення',
  [PermissionType.ordersDelete]: 'Видалити замовлення',
  [PermissionType.establishmentsCreate]: 'Додавання закладів',
  [PermissionType.establishmentsUpdate]: 'Редагування закладів',
  [PermissionType.establishmentsDelete]: 'Видалення закладів',
  [PermissionType.networkEdit]: 'Редагування мережі',
  [PermissionType.tablesView]: 'Перегляд столів',
  [PermissionType.tablesCreate]: 'Додавання столів',
  [PermissionType.tablesEdit]: 'Редагування столів',
  [PermissionType.tablesDelete]: 'Видалення столів',
  [PermissionType.usersView]: 'Перегляд користувачів',
  [PermissionType.usersEdit]: 'Редагування користувачів',
  [PermissionType.usersDelete]: 'Видалення користувачів',
  [PermissionType.invitationsView]: 'Перегляд запрошень',
  [PermissionType.invitationsCreate]: 'Створення запрошень',
  [PermissionType.invitationsDelete]: 'Видалення запрошень',
  [PermissionType.rolesView]: 'Перегляд ролей',
  [PermissionType.rolesUpdate]: 'Редагування ролей',
  [PermissionType.rolesCreate]: 'Створення ролей',
  [PermissionType.rolesDelete]: 'Видалення ролей',
};
