// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QrMenuAPI.Core;

#nullable disable

namespace QrMenuAPI.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260216110011_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QrMenuAPI.Core.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("NetworkId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_network_id_name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.EstablishmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.HasKey("Id")
                        .HasName("pk_establishments");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_establishments_name");

                    b.HasIndex("NetworkId")
                        .HasDatabaseName("ix_establishments_network_id");

                    b.ToTable("establishments", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.InvitationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("integer")
                        .HasColumnName("establishment_id");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Surname")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("surname");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("integer")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("EstablishmentId")
                        .HasDatabaseName("ix_invitations_establishment_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_invitations_role_id");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_invitations_target_user_id");

                    b.HasIndex("Phone", "EstablishmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_phone_establishment_id");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.NetworkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_networks");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_networks_name");

                    b.ToTable("networks", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.OrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp with time zone");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CustomerFullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_full_name");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("integer")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer")
                        .HasColumnName("table_id");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_sum");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_orders_created_by_user_id");

                    b.HasIndex("EstablishmentId")
                        .HasDatabaseName("ix_orders_establishment_id");

                    b.HasIndex("TableId")
                        .HasDatabaseName("ix_orders_table_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.OrderItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category_name_snapshot");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("line_total");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<decimal>("PriceSnapshot")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_snapshot");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name_snapshot");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_items_product_id");

                    b.HasIndex("OrderId", "ProductId")
                        .HasDatabaseName("ix_order_items_order_id_product_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.OrderStaffEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_order_staff");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_order_staff_user_id");

                    b.HasIndex("OrderId", "UserId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_order_staff_order_id_user_id_role");

                    b.ToTable("order_staff", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.OrderStatusHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by_user_id");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer")
                        .HasColumnName("from_status");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_order_status_history");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("ix_order_status_history_changed_by_user_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_status_history_order_id");

                    b.ToTable("order_status_history", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("NetworkId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_products_network_id_name");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.ProductPriceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("integer")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_prices");

                    b.HasIndex("EstablishmentId")
                        .HasDatabaseName("ix_product_prices_establishment_id");

                    b.HasIndex("ProductId", "EstablishmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_prices_product_id_establishment_id");

                    b.ToTable("product_prices", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NetworkId")
                        .HasDatabaseName("ix_roles_network_id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.RolePermissionEntity", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionType")
                        .HasColumnType("integer")
                        .HasColumnName("permission_type");

                    b.HasKey("RoleId", "PermissionType")
                        .HasName("pk_role_permissions");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.TableEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("integer")
                        .HasColumnName("establishment_id");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("pk_tables");

                    b.HasIndex("EstablishmentId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_tables_establishment_id_number");

                    b.ToTable("tables", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NetworkId")
                        .HasDatabaseName("ix_users_network_id");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.UserEstablishmentEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("integer")
                        .HasColumnName("establishment_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "EstablishmentId")
                        .HasName("pk_user_establishments");

                    b.HasIndex("EstablishmentId")
                        .HasDatabaseName("ix_user_establishments_establishment_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_establishments_role_id");

                    b.ToTable("user_establishments", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.UserSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.CategoryEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.NetworkEntity", "Network")
                        .WithMany()
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_networks_network_id");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.EstablishmentEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.NetworkEntity", "Network")
                        .WithMany("Establishments")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_establishments_networks_network_id");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.InvitationEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.EstablishmentEntity", "Establishment")
                        .WithMany("Invitations")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_establishments_establishment_id");

                    b.HasOne("QrMenuAPI.Core.Entities.RoleEntity", "Role")
                        .WithMany("Invitations")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_roles_role_id");

                    b.HasOne("QrMenuAPI.Core.Entities.UserEntity", "TargetUser")
                        .WithMany("Invitations")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_invitations_users_target_user_id");

                    b.Navigation("Establishment");

                    b.Navigation("Role");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.OrderEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.UserEntity", "CreatedByUser")
                        .WithMany("OrdersCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_orders_users_created_by_user_id");

                    b.HasOne("QrMenuAPI.Core.Entities.EstablishmentEntity", "Establishment")
                        .WithMany("Orders")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_establishments_establishment_id");

                    b.HasOne("QrMenuAPI.Core.Entities.TableEntity", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_orders_tables_table_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Establishment");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.OrderItemEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.OrderEntity", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.HasOne("QrMenuAPI.Core.Entities.ProductEntity", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_order_items_products_product_id");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.OrderStaffEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.OrderEntity", "Order")
                        .WithMany("Staff")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_staff_orders_order_id");

                    b.HasOne("QrMenuAPI.Core.Entities.UserEntity", "User")
                        .WithMany("AssignedOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_staff_users_user_id");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.OrderStatusHistoryEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.UserEntity", "ChangedByUser")
                        .WithMany("StatusChanges")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_status_history_users_changed_by_user_id");

                    b.HasOne("QrMenuAPI.Core.Entities.OrderEntity", "Order")
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_status_history_orders_order_id");

                    b.Navigation("ChangedByUser");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.ProductEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.HasOne("QrMenuAPI.Core.Entities.NetworkEntity", "Network")
                        .WithMany()
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_networks_network_id");

                    b.Navigation("Category");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.ProductPriceEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.EstablishmentEntity", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_prices_establishments_establishment_id");

                    b.HasOne("QrMenuAPI.Core.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_prices_products_product_id");

                    b.Navigation("Establishment");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.RoleEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.NetworkEntity", "Network")
                        .WithMany("Roles")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_networks_network_id");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.RolePermissionEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.RoleEntity", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.TableEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.EstablishmentEntity", "Establishment")
                        .WithMany("Tables")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tables_establishments_establishment_id");

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.UserEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.NetworkEntity", "Network")
                        .WithMany("Users")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_networks_network_id");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.UserEstablishmentEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.EstablishmentEntity", "Establishment")
                        .WithMany("UserEstablishment")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_establishments_establishments_establishment_id");

                    b.HasOne("QrMenuAPI.Core.Entities.RoleEntity", "Role")
                        .WithMany("UserEstablishment")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_establishments_roles_role_id");

                    b.HasOne("QrMenuAPI.Core.Entities.UserEntity", "User")
                        .WithMany("UserEstablishment")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_establishments_users_user_id");

                    b.Navigation("Establishment");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.UserSessionEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.UserEntity", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.EstablishmentEntity", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Orders");

                    b.Navigation("Tables");

                    b.Navigation("UserEstablishment");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.NetworkEntity", b =>
                {
                    b.Navigation("Establishments");

                    b.Navigation("Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.OrderEntity", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Staff");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.ProductEntity", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.RoleEntity", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Permissions");

                    b.Navigation("UserEstablishment");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.TableEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.UserEntity", b =>
                {
                    b.Navigation("AssignedOrders");

                    b.Navigation("Invitations");

                    b.Navigation("OrdersCreated");

                    b.Navigation("Sessions");

                    b.Navigation("StatusChanges");

                    b.Navigation("UserEstablishment");
                });
#pragma warning restore 612, 618
        }
    }
}
