// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QrMenuAPI.Core;

#nullable disable

namespace QrMenuAPI.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130171701_Tables")]
    partial class Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QrMenuAPI.Core.Entities.EstablishmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.HasKey("Id")
                        .HasName("pk_establishments");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_establishments_name");

                    b.HasIndex("NetworkId")
                        .HasDatabaseName("ix_establishments_network_id");

                    b.ToTable("establishments", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.InvitationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("integer")
                        .HasColumnName("establishment_id");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Surname")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("surname");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("integer")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("EstablishmentId")
                        .HasDatabaseName("ix_invitations_establishment_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_invitations_role_id");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_invitations_target_user_id");

                    b.HasIndex("Phone", "EstablishmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_phone_establishment_id");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.NetworkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_networks");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_networks_name");

                    b.ToTable("networks", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NetworkId")
                        .HasDatabaseName("ix_roles_network_id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.RolePermissionEntity", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionType")
                        .HasColumnType("integer")
                        .HasColumnName("permission_type");

                    b.HasKey("RoleId", "PermissionType")
                        .HasName("pk_role_permissions");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.TableEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("integer")
                        .HasColumnName("establishment_id");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("pk_tables");

                    b.HasIndex("EstablishmentId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_tables_establishment_id_number");

                    b.ToTable("tables", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NetworkId")
                        .HasDatabaseName("ix_users_network_id");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.UserEstablishmentEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("integer")
                        .HasColumnName("establishment_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "EstablishmentId")
                        .HasName("pk_user_establishments");

                    b.HasIndex("EstablishmentId")
                        .HasDatabaseName("ix_user_establishments_establishment_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_establishments_role_id");

                    b.ToTable("user_establishments", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.UserSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.EstablishmentEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.NetworkEntity", "Network")
                        .WithMany("Establishments")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_establishments_networks_network_id");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.InvitationEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.EstablishmentEntity", "Establishment")
                        .WithMany("Invitations")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_establishments_establishment_id");

                    b.HasOne("QrMenuAPI.Core.Entities.RoleEntity", "Role")
                        .WithMany("Invitations")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_roles_role_id");

                    b.HasOne("QrMenuAPI.Core.Entities.UserEntity", "TargetUser")
                        .WithMany("Invitations")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_invitations_users_target_user_id");

                    b.Navigation("Establishment");

                    b.Navigation("Role");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.RoleEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.NetworkEntity", "Network")
                        .WithMany("Roles")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_networks_network_id");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.RolePermissionEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.RoleEntity", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.TableEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.EstablishmentEntity", "Establishment")
                        .WithMany("Tables")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tables_establishments_establishment_id");

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.UserEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.NetworkEntity", "Network")
                        .WithMany("Users")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_networks_network_id");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.UserEstablishmentEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.EstablishmentEntity", "Establishment")
                        .WithMany("UserEstablishment")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_establishments_establishments_establishment_id");

                    b.HasOne("QrMenuAPI.Core.Entities.RoleEntity", "Role")
                        .WithMany("UserEstablishment")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_establishments_roles_role_id");

                    b.HasOne("QrMenuAPI.Core.Entities.UserEntity", "User")
                        .WithMany("UserEstablishment")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_establishments_users_user_id");

                    b.Navigation("Establishment");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.UserSessionEntity", b =>
                {
                    b.HasOne("QrMenuAPI.Core.Entities.UserEntity", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.EstablishmentEntity", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Tables");

                    b.Navigation("UserEstablishment");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.NetworkEntity", b =>
                {
                    b.Navigation("Establishments");

                    b.Navigation("Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.RoleEntity", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Permissions");

                    b.Navigation("UserEstablishment");
                });

            modelBuilder.Entity("QrMenuAPI.Core.Entities.UserEntity", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Sessions");

                    b.Navigation("UserEstablishment");
                });
#pragma warning restore 612, 618
        }
    }
}
